Roll back slf4j update, because
Run ARGS="-client JAVA_NET -abort-after 100 deutschlandfunk -d deutschlandfunk"
11
Args: -client JAVA_NET -abort-after 100 deutschlandfunk -d deutschlandfunk
12
Error: Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
13
	at de.sfuhrm.radiorecorder.Main.<clinit>(Main.java:47)
14
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
15
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
16
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
17
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
18
	... 1 more